### ISSUE TITLE
Add Safari support

### ISSUE THREAD

**Issue by fregante** [sindresorhus/hide-files-on-github#102]
I'm missing it on Safari. I'd like to see it there too.

Configuration can be copied from https://github.com/OctoLinker/OctoLinker

Starting point: https://github.com/OctoLinker/OctoLinker/pull/1167

**Comment by fregante** [comment]
Bump 🥲

**Comment by sindresorhus** [comment]
I don't have time to do this. Maybe move it into Refined GitHub?

**Comment by fregante** [comment]
> Maybe move it into Refined GitHub?

I'd love to, but this extension requires configurability. It'd probably be more productive to turn it into a user script

**Comment by sindresorhus** [comment]
I think I'm more likely to do this issue when we have managed to fully automate Safari releases for Refined GitHub (so we could copy it here).

**Comment by fregante** [comment]
👍 

Releases aren't much of an issue here though 😅 The last one was 363 days ago.
