### ISSUE TITLE
Does not work anymore with "New Repository Overview" enabled

### ISSUE THREAD

**Issue by engelju** [sindresorhus/hide-files-on-github#107]
If you enable the "New Repository Overview" feature preview, this extension sadly no longer works:

<img width="755" alt="Screenshot 2023-11-20 at 13 17 40" src="https://github.com/sindresorhus/hide-files-on-github/assets/2188152/81eeec25-2e8e-4cb2-8bd5-0fb5913b4683">

Working (feature preview not enabled):

<img width="559" alt="Screenshot 2023-11-20 at 13 16 27" src="https://github.com/sindresorhus/hide-files-on-github/assets/2188152/0842c972-d08b-4920-84ba-0a0313e35516">

Not working (feature preview enabled):

<img width="548" alt="Screenshot 2023-11-20 at 13 16 12" src="https://github.com/sindresorhus/hide-files-on-github/assets/2188152/4f48bc1e-15b3-4d2a-9d81-03c23f6ea90c">

I hope we can update this extension somehow accordingly.

**Comment by sindresorhus** [comment]
This extension is now deprecated.
