### ISSUE TITLE
Toggle Button does not recall application state after MutationObserver fires

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/hide-files-on-github#21]
Every time the  `addToggleBtn()` function is called, and the Toggle Button is not loaded (and it never is  after the Mutation occurred, which is why it needs to be continuously added), this line of code is run:
```js
const toggleBtn = createHtml('<a class="hide-files-btn btn btn-sm">Show dotfiles</a>');
```
Which indiscriminately sets the button.textContent to "Show dotfiles", ignoring the application state before the Mutation occurred. 

I am happy to help with a PR if you agree this is a problem.

**Comment by radiovisual** [comment]
You can recreate this problem by loading any github page, clicking the Toggle Button to say "Hide dotfiles", then clicking any of the tabs at the top "Issues", "Pull Requests", etc, and then clicking back to "Code", then you will notice that the dotfiles are still showing, but the button now says "Show dotfiles"

**Comment by sindresorhus** [comment]
Yeah, looks like a bug. A pull request would be much appreciated :)
