### ISSUE TITLE
The toggle button shouldn't show if you've chosen only to dim files.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/hide-files-on-github#35]
Currently if you've chosen `dimmed` instead of `hidden` in the options, the toggle button still shows up, but it just let's you toggle between `dimmed` and `not dimmed` which is sort of useless.

**Comment by sindresorhus** [comment]
👍

**Comment by radiovisual** [comment]
Good point. 

PR #36 should fix that.

**Comment by sindresorhus** [comment]
Thanks @radiovisual. Published :)
