### ISSUE TITLE
Minor usability annoyance.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/hide-files-on-github#37]
So, I love the new "show/hide" button, but I have noticed one minor annoyance.

The "show" button is at the bottom, but GitHub lists dotfiles at the top of the listing.

This means, to show dotfiles, I need to scroll to the bottom, click "show", then scroll back to the top.

I think putting the button at the bottom of the list was a mistake, it should go at the top.

**Comment by radiovisual** [comment]
I like the idea of adding the button to the top as well, for the same reasons you do. But I also like it at the bottom sometimes (because it gets it out of the way when I am not really using it), so what making it an option, so users can decide, and then have the default option be at the top?

**Comment by sindresorhus** [comment]
I don't like options. I think we should find on way to do it and stick with it.

**Comment by radiovisual** [comment]
Ok, then putting it the top is probably the best default.

**Comment by radiovisual** [comment]
It is **much** better at the top. 👍

**Comment by sindresorhus** [comment]
Fixed by #40.
