### ISSUE TITLE
Don't make me choose between dimming and hiding.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/hide-files-on-github#38]
I liked the dimmed look, but, now I have to choose between dimming and hiding.

Instead of the "dimmed" / "hidden" choice. I think there should be two checkboxes. 

- [ ] Hide dotfiles
- [ ] Dim dotfiles

If you select both, they default to hidden, but when you expand with the button they show up dimmed.

If you unselect both, the extension is essentially disabled (Sort of pointless if someone chooses that, but whatever).

If you only check one or the other, you git similar behavior to what we have now (dimmed but not hideable with no button, or hideable but not dimmed).

**Comment by sindresorhus** [comment]
I think they should just be dimmed when expanded in `hidden` mode. I've often had to look twice to find the dotfiles when I click `Show dotfiles`. Having them dimmed makes it clear where they are. Thoughts?

**Comment by jamestalmage** [comment]
👍 That's what I would pick if given the option, so I'm fine with it being automatic.

**Comment by jamestalmage** [comment]
So...
1. Always dim.
2. Options are reduced to a hide / don't hid checkbox and the regex.

Next Question,

Should the hide/show button always be there? Regardless of whether or not they've checked `2`? Meaning, they can always hide, but we just give them a choice as to what the default state is?

**Comment by radiovisual** [comment]
> So...
> 1. Always dim.
> 2. Options are reduced to a hide / don't hid checkbox and the regex.

👍 

I like the idea of always dim, since this extension is all about hiding the dotfiles, it should also make it easy for you to identify them when shown. 

@jamestalmage , I am not sure I understand the question:

> Should the hide/show button always be there? Regardless of whether or not they've checked 2?
> Meaning, they can always hide, but we just give them a choice as to what the default state is? 

Can you explain? Do you mean you have specific criteria for when the toggle button should not be visible?

**Comment by sindresorhus** [comment]
Fixed by #40.
