### ISSUE TITLE
Bitbucket alternative

### ISSUE THREAD

**Issue by Zhouzi** [sindresorhus/hide-files-on-github#47]
Thanks for building this! 🎉 

I hope you don't mind but I thought it would be helpful to inform that I built a similar extension for Bitbucket: [hide-files-from-bitbucket-pr](https://github.com/Zhouzi/hide-files-from-bitbucket-pr)

This is just for reference, feel free to close and ignore this issue.

**Comment by sindresorhus** [comment]
Nice! Happy to link to it at the bottom of the readme if you do a PR.

Same format as done here: https://github.com/sindresorhus/refined-github#related
