### ISSUE TITLE
Allow multiple regular expressions

### ISSUE THREAD

**Issue by popey456963** [sindresorhus/hide-files-on-github#50]
Would be nice.

**Comment by sindresorhus** [comment]
Why?

**Comment by popey456963** [comment]
Because editing one massive regular expression is a lot harder than editing lots of smaller ones.  Similar to the reason one doesn't put all of their code on one line but instead spaces it out amongst multiple lines.

```javascript
^\.|^license|^cname$|^version$|^(patents|authors|contributors|acknowledgments|backers)(\.|$)|^(issue|pull_request)_template\.md$|^(appveyor|circle|codecov)\.yml$|^(yarn|Gemfile)\.lock$|^npm-shrinkwrap\.json$|\.sublime-project$|^(tsconfig|typings|tslint|tsfmt)\.json$|^coffeelint\.json$|^(karma|protractor|sauce).*\.js$|^testem(\.[\w-]+)?\.(json|js)$|^yuidoc\.json$|^stylelint-config\.json
```

Is not the most appealing regular expression.  Whereas in my opinion:

```javascript
^\.
^license
^cname$
^version$
^(patents|authors|contributors|acknowledgments|backers)(\.|$)
^(issue|pull_request)_template\.md$
^(appveyor|circle|codecov)\.yml$
^(yarn|Gemfile)\.lock$
^npm-shrinkwrap\.json$|\.sublime-project$
^(tsconfig|typings|tslint|tsfmt)\.json$
^coffeelint\.json$
^(karma|protractor|sauce).*\.js$
^testem(\.[\w-]+)?\.(json|js)$
^yuidoc\.json$
^stylelint-config\.json
```

Is much nicer.

**Comment by popey456963** [comment]
As a point, it would also be simple to implement this.  If multiple lines exist just split on them and then join them with pipes to form the single regular expression.

**Comment by sindresorhus** [comment]
Ah yeah, good point. Pull request welcome :)

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/hide-files-on-github/commit/1157a69fa59df4ab78d7df61a251087a425e49af.

**Comment by bfred-it** [comment]
Hah I didn't even realize that it had been requested 😁
