### ISSUE TITLE
Let's add package-lock.json to nonessentials list!

### ISSUE THREAD

**Issue by revelt** [sindresorhus/hide-files-on-github#52]
Hi all!
Should we add `package-lock.json` among _nonessentials_? It's kindof meaningless when browsing GitHub page, isn't it?

**Comment by radiovisual** [comment]
Seems it is already on the list: https://github.com/sindresorhus/hide-files-on-github/blob/master/extension/api.js#L15

**Comment by revelt** [comment]
nah,

![not_being_hidden](https://user-images.githubusercontent.com/8344688/27044906-26ab938e-4f97-11e7-9fbf-1429d7d07e20.png)

is it working at yours? I can see it's not hidden on your `eth-price` too for example..

**Comment by radiovisual** [comment]
Yeah, you are right. It's not working. It IS added to the defaults in api.js, but when I inspect the contents of the `1.7.0` release archive, the `package-lock.json` entry is not there. This just means that [this line of code](https://github.com/sindresorhus/hide-files-on-github/blob/master/extension/api.js#L15) has not made it to the published version of the extension yet.

**Comment by radiovisual** [comment]
I have confirmed that `package-lock.json` files are hidden when you use the source code from this repository as an extension, so I think this issue can be closed after a new version is published to the Chrome Web Store

**Comment by sindresorhus** [comment]
New release is out.
