### ISSUE TITLE
1.8.0 errors out when reinstalled on MacOS x Chrome?

### ISSUE THREAD

**Issue by revelt** [sindresorhus/hide-files-on-github#53]
hi all,

I saw 1.8.0 was released, but I couldn't find any button on Chrome to trigger a plugin update, so I removed `hide-files-on-github` completely and installed it again. That is, _tried to install_, because I got this error message:

![screen shot 2017-06-13 at 12 36 58](https://user-images.githubusercontent.com/8344688/27080808-76fe2164-5035-11e7-96f6-492e72e0c3e4.png)

Please check on your computers, is it happening for everybody, or is it just me?

cheers
Roy

**Comment by radiovisual** [comment]
I can confirm that it happens to me as well.

**Comment by radiovisual** [comment]
Seems this problem has been resolved via `1.8.1`

**Comment by revelt** [comment]
New version works fine for me now. I'll close. Good job guys!
