### ISSUE TITLE
Release on Firefox

### ISSUE THREAD

**Issue by Mte90** [sindresorhus/hide-files-on-github#54]
Now with webextension is possible to port a chrome extension very easily :-)

**Comment by sindresorhus** [comment]
No thanks, I don't use Firefox. You can use it from GitHub if you want.

**Comment by rugk** [comment]
Here is how you do it, BTW: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

Has anyone tried whether that add-on needs changes?

**Comment by salmanulfarzy** [comment]
Yes. Works with minimal changes and currently using this as local Firefox add-on. 

**Fork**: [salmanulfarzy/hide-files-on-github@firefox](https://github.com/salmanulfarzy/hide-files-on-github/tree/firefox)
**Commits** : https://github.com/salmanulfarzy/hide-files-on-github/commit/37eda24227fa7d4da6d399d5f1dcc1455aa42654, https://github.com/salmanulfarzy/hide-files-on-github/commit/2813b56099eed744d0bfad770883f88f83319712

Build extension from repo using `web-ext` and sideload to Firefox.

**Comment by salmanulfarzy** [comment]
Yes. Works with minimal changes and currently using this as local Firefox add-on. 

**Fork**: [salmanulfarzy/hide-files-on-github@firefox](https://github.com/salmanulfarzy/hide-files-on-github/tree/firefox)
**Commits** : https://github.com/salmanulfarzy/hide-files-on-github/commit/37eda24227fa7d4da6d399d5f1dcc1455aa42654, https://github.com/salmanulfarzy/hide-files-on-github/commit/2813b56099eed744d0bfad770883f88f83319712

Build extension from repo using `web-ext` and sideload to Firefox.

**Comment by Mte90** [comment]
Can you release on Addons.mozilla.org?

**Comment by salmanulfarzy** [comment]
Will submit to AMO if #70 is not accepted.
