### ISSUE TITLE
Support non-root listings

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/hide-files-on-github#55]
As mentioned by a review: https://chrome.google.com/webstore/detail/hide-files-on-github/lpnakhpaodhdkleejaehlapdhbgjbddp/reviews

> Only work for files at root directory

e.g. https://github.com/babel/babel/tree/7.0/packages/babel-cli

**Comment by sindresorhus** [comment]
Not something I would ever need, but happy to take a pull request if anyone wants it.

**Comment by radiovisual** [comment]
I think this makes sense for larger repos. I have run into this a few times. You get used to the way this extension works, so it throws you off when you visit a larger repo with "non-essential" files outside of the root, and it gives the impression that the extension is broken. 

I think I looked into this feature a while back, but there was something preventing me from getting to it to work properly, can't remember what it is now, but I think was either that GitHub markup was in flux, or the non-root tables weren't specific enough to detect, something along those lines, whatever it was, it was messing with our detections, but maybe we won't have any of those problems if we try again.
