### ISSUE TITLE
Automate publish

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/hide-files-on-github#62]
With: https://github.com/DrewML/chrome-webstore-upload-cli

This one is not going to be updated that often, so I think it makes most the sense to do it on new Git tags.

**Comment by radiovisual** [comment]
This is a good idea. How would you like to handle the Google API credentials? Once we have credentials to use (clientId, a clientSecret and a refreshToken) we have to decide how (and if) we want to expose them to the repo, and how that fits into the automated publish process.

**Comment by sindresorhus** [comment]
Same as with https://github.com/sindresorhus/refined-github, I will just add the credentials when everything else is set up.
