### ISSUE TITLE
Hide readme.md

### ISSUE THREAD

**Issue by pablopunk** [sindresorhus/hide-files-on-github#64]
I don't know if this has been discussed before but, why not hiding the `readme.md`<sup>1</sup> as it's always gonna be shown below<sup>2</sup>?

<img width="987" alt="ss" src="https://user-images.githubusercontent.com/4324982/29048946-9b7ec0ec-7bd3-11e7-89be-0ca69cf3e812.png">

**Comment by sindresorhus** [comment]
👍
