### ISSUE TITLE
recognise rollup.config.js?

### ISSUE THREAD

**Issue by revelt** [sindresorhus/hide-files-on-github#67]
Rollup standard config file is `rollup.config.js` and it's currently not recognised:

![screen shot 2017-11-12 at 21 14 37](https://user-images.githubusercontent.com/8344688/32703497-bf0992e6-c7ee-11e7-8cc4-708f55c707c6.png)

Should we add it to the list?

**Comment by bfred-it** [comment]
No build files are included of any kind at the moment, I'm not sure that they should.

**Comment by revelt** [comment]
ok let's close
