### ISSUE TITLE
Enterprise GitHub?

### ISSUE THREAD

**Issue by kylebarron** [sindresorhus/hide-files-on-github#68]
Can this work with enterprise github as well?

**Comment by sindresorhus** [comment]
I could, yes, but not something I'm going to work on. I'll leave this open as "PR welcome. It could use the same approach as done here: https://github.com/sindresorhus/refined-github/blob/1e2428126e1e4eabe4e822eac6f2efd9263f02cc/source/background.js#L53-L55

**Comment by hipstersmoothie** [comment]
I'm gonna try to take a swing at this. It seems like a pretty big overhaul though. As I see it the steps would be:

- [ ] Emulate `refined-github`'s Webpack/Babel Configuration
- [ ] Convert options to https://github.com/bfred-it/webext-options-sync
- [ ] Use https://github.com/bfred-it/webext-dynamic-content-scripts and https://github.com/bfred-it/webext-domain-permission-toggle

**Comment by bfred-it** [comment]
Only the third point is necessary for this

**Comment by hipstersmoothie** [comment]
@bfred-it I tried doing it the non webpack way from your readmes and couldn't get it to work.

**Comment by bfred-it** [comment]
The error you mentioned on that repo was because it cannot find the file. They need to be in the same folder. The file is not node-specific

**Comment by hipstersmoothie** [comment]
I see your comment now. Would you advise on a build step that moves the files from node_modules to the extension directory? I would be hesitant to just move the files, since they could get out of date.

**Comment by bfred-it** [comment]
No need, I don’t update those modules nearly that often

**Comment by hipstersmoothie** [comment]
Ok! As long as @sindresorhus is ok with it I'll just move the files to the extension folder.

**Comment by bfred-it** [comment]
`extension/libs` would be best, that’s how they were set in another Sindre’s extension
