### ISSUE TITLE
Suggestion: Hide .gitkeep files

### ISSUE THREAD

**Issue by AlexejheroYTB** [sindresorhus/hide-files-on-github#81]
Cross-posted from sindresorhus/refined-github#2208

---

## Suggestion
In some repos, there may be empty folders containing a `.gitkeep` file. This is usually done so that the folders appear in the repo, even though they dont contain any files (maybe the folders themselves store information in their name).

The link to open the folder is redundant because inside it there is only a 0 KB `.gitkeep` file.

Refind github could check if there is only one file in the folder and if it has 0 KB, and if that is the case, completely remove the link to open the folder.

## Example URL

https://github.com/AlexejheroYTB/Dlockly/tree/master/blocks/custom

Example of folder that this could apply to: `002 [sep]`'

## Images
This feature could look something like this: 

![image](https://user-images.githubusercontent.com/32238504/60742653-dd580000-9f76-11e9-8014-54f1e655e563.png)

**Comment by bfred-it** [comment]
Just one problem: this would require an API call, which would slow down the hiding. Currently it's great because you never see the list of files. #78

**Comment by fregante** [comment]
Closing for that reason, it would require a rewrite that would make it slower
