### ISSUE TITLE
Firefox Mobile / Android

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/hide-files-on-github#83]
Hey there. Not sure, but I can find Refined GitHub as an extension for Firefox Android, but not the OctoLinker and Hide Files on GitHub. Is it something specific or not?

Seems like Refined GitHub is available for both.
https://addons.mozilla.org/en-US/firefox/addon/refined-github-/
https://addons.mozilla.org/en-US/android/addon/refined-github-/

What's the difference between the two firefox versions, from extensions perspective? What's needed to be changed to be available for Android?

Until recently (mostly?) none of them were possible on Firefox and now I'm seeing that they are which is cool because they are the absolute requirement to me to be able to work and browse. That was one of the reasons why I'm still on Chrome-based browsers.

**Comment by fregante** [comment]
I think it just needs to be enabled on Mozilla Addons. The extension is identical

**Comment by sindresorhus** [comment]
I don't have access to the extension on AMO, so I'm gonna let @fregante enable it.

**Comment by fregante** [comment]
AMO login isn't working at the moment, I'll try again later.

**Comment by fregante** [comment]
https://addons.mozilla.org/en-US/android/addon/hide-files-on-github-/
