### ISSUE TITLE
Something is wrong for few weeks (401 errors)

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/hide-files-on-github#86]
Almost constantly it reject to hide the files. In very rare cases it succeeds to hide them. Seems like 401 errors in the console.

![2020-03-14-224011_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/76689996-9f05fb00-6644-11ea-8a1b-88b183f4cb57.png)

Any ideas?

```
Chromium
Version 79.0.3945.130 (Official Build) Arch Linux (64-bit)
```

**Comment by fregante** [comment]
1. We don't have any `inject.js` scripts
2. This appears to be related to an expired API token
