### ISSUE TITLE
Chrome Store rejected new versions (privacy info)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/hide-files-on-github#92]
> Publish condition not met: To publish your item, you must provide mandatory privacy information. This can be done in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole.

Related Refined GitHub issue, probably parts of it can be copied: https://github.com/sindresorhus/refined-github/issues/2685

@sindresorhus   can you look into it?

**Comment by sindresorhus** [comment]
Done. I'll close this when the update has been reviewed and accepted.

**Comment by fregante** [comment]
Is this still pending review?

**Comment by yakov116** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I just got the same rejection for <a href="https://t.co/qpBOqwHb12">https://t.co/qpBOqwHb12</a> Same generic non-actionable rejection...</p>&mdash; Sindre Sorhus (@sindresorhus) <a href="https://twitter.com/sindresorhus/status/1249581043440476161?ref_src=twsrc%5Etfw">April 13, 2020</a></blockquote>

**Comment by fregante** [comment]
> @sindresorhus, I think the review team has sorted this one out. Please resubmit when you have a chance
> 
> Right now the description is pretty minimal. I'd also recommend adding a line to the description indicating that this extension is compatible with self-hosted GitHub Enterprise

https://twitter.com/DotProto/status/1250943456286961666 April 17

**Comment by sindresorhus** [comment]
I just resubmitted for review now.

**Comment by sindresorhus** [comment]
Should be good now.
