### ISSUE TITLE
flash of unstyled content on firefox

### ISSUE THREAD

**Issue by SimonSiefke** [sindresorhus/hide-files-on-github#93]
I'm using this extension with firefox and before it shows the github page there is always a short flash of unstyled content. 

![fouc](https://user-images.githubusercontent.com/23744935/79642186-5fc74e80-819c-11ea-84bc-8a12d7a68cd2.gif)

P.S. Thanks for all the great work! :)

**Comment by fregante** [comment]
I've experienced this too and it's ridiculous. I don't know why this would be caused by an extension.

**Comment by fregante** [comment]
Confirmed:
- it happens on the code tab only
- if the extension is active
