### ISSUE TITLE
Extension doesn't work with new github design

### ISSUE THREAD

**Issue by maratori** [sindresorhus/hide-files-on-github#96]
I've enabled Feature preview on github called `Repository refresh`.
It uses completely different DOM layout, so the extension doesn't work any more.

![image](https://user-images.githubusercontent.com/16486128/85208119-86d60400-b336-11ea-948f-470a281be789.png)

![image](https://user-images.githubusercontent.com/16486128/85208136-9e14f180-b336-11ea-9b1c-9f93dcec4623.png)

**Comment by sindresorhus** [comment]
The new design is now live for everyone.

**Comment by tunnckoCore** [comment]
Yep... pretty sad thing. It landed too fast and changed too much. I really hate all of it.

**Comment by tunnckoCore** [comment]
Yes :tada:
